<?php
/**
 * @file
 * Code for the c21 feature.
 */

include_once 'c21.features.inc';

// Give each of the date format types a machine name.
define('C21_DATE_TYPE_VERY_SHORT', 'c21_date_type_very_short');
define('C21_DATE_TYPE_VERY_LONG', 'c21_date_type_very_long');

// Define the date formats to be passed to date().
define('C21_DATE_FORMAT_VERY_SHORT', 'Y');
define('C21_DATE_FORMAT_SHORT', 'M d, Y');
define('C21_DATE_FORMAT_MEDIUM', 'F d, Y');
define('C21_DATE_FORMAT_LONG', 'F d Y, g:ia');
define('C21_DATE_FORMAT_VERY_LONG', 'l, F d Y, g:ia');

/**
 * Implements hook_workbench_content_alter().
 */
function c21_workbench_content_alter(&$output) {
  if (module_exists('c21_listings')) {
    $output['c21_workbench_reports'] = array(
      '#title' => t('Reports'),
      '#attributes' => array(
        'class' => array('left', 'clearfix'),
      ),
      'report_links' => array('#markup' => c21_listings_reports_links()),
      '#theme' => 'workbench_element',
    );
    $output['#attached']['css'][] = drupal_get_path('module', 'c21') . '/css/c21_workbench.css';
    unset($output['workbench_current_user']);
  }

  $output['c21_workbench_edits_by_user'] = $output['workbench_edited'];
  $output['c21_workbench_edits_by_user']['#view'] = 'c21_workbench_edits_by_user';
  unset($output['workbench_edited']);

  $output['c21_workbench_recent_content'] = $output['workbench_recent_content'];
  $output['c21_workbench_recent_content']['#view'] = 'c21_workbench_recent_content';
  unset($output['workbench_recent_content']);

}

/**
 * Implements hook_date_formats().
 */
function c21_date_formats() {
  $formats = array();

  $formats[] = array(
    'type' => C21_DATE_TYPE_VERY_SHORT,
    'format' => C21_DATE_FORMAT_VERY_SHORT,
    'locales' => array(),
  );
  $formats[] = array(
    'type' => 'short',
    'format' => C21_DATE_FORMAT_SHORT,
    'locales' => array(),
  );
  $formats[] = array(
    'type' => 'medium',
    'format' => C21_DATE_FORMAT_MEDIUM,
    'locales' => array(),
  );
  $formats[] = array(
    'type' => 'long',
    'format' => C21_DATE_FORMAT_LONG,
    'locales' => array(),
  );
  $formats[] = array(
    'type' => C21_DATE_TYPE_VERY_LONG,
    'format' => C21_DATE_FORMAT_VERY_LONG,
    'locales' => array(),
  );

  return $formats;
}

/**
 * Implements hook_date_format_types().
 */
function c21_date_format_types() {
  $types = array();
  $types[C21_DATE_TYPE_VERY_SHORT] = t('Very Short');
  $types[C21_DATE_TYPE_VERY_LONG] = t('Very Long');
  return $types;
}
