<?php

/**
 * Implements hook_install().
 */
function c21_install() {
  // Enabe the escrow theme.
  theme_enable(array('escrow'));

  // Create an empty page callback for the homepage and set the default homepage
  // to point to it.
  $callback = new stdClass();

  $callback->path = 'home';
  $callback->page_title = '';
  $callback->created = REQUEST_TIME;
  $callback->changed = REQUEST_TIME;

  empty_page_save_callback($callback);
  variable_set('site_frontpage', 'home');
}
