<?php
/**
 * @file
 * Code for the c21 feature.
 */

include_once 'c21.features.inc';

// Give each of the date format types a machine name.
define('C21_DATE_TYPE_VERY_SHORT', 'c21_date_type_very_short');
define('C21_DATE_TYPE_VERY_LONG', 'c21_date_type_very_long');

// Define the date formats to be passed to date().
define('C21_DATE_FORMAT_VERY_SHORT', 'Y');
define('C21_DATE_FORMAT_SHORT', 'M d, Y');
define('C21_DATE_FORMAT_MEDIUM', 'F d, Y');
define('C21_DATE_FORMAT_LONG', 'F d Y, g:ia');
define('C21_DATE_FORMAT_VERY_LONG', 'l, F d Y, g:ia');

/**
 * Implements hook_block_info().
 */
function c21_block_info() {
  $blocks['c21_footer'] = array(
    'info' => t('Footer'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;
}

function c21_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
    case 'c21_footer':
      $block['subject'] = '';
      $block['content'] = array(
        'address_dingmans' => array(
          '#attributes' => array(
            'class' => array('address', 'dingmans'),
          ),
          '#theme_wrappers' => array('container'),
          '#markup' => '<span class="street">1869 Route 739</span><span class="city-state-zip">Dingmans Ferry, PA 18328</span><a class="phone" href="tel:18004584855">1-800-458-4855</a><a class="phone" href="tel:5708289591">(570) 828-9591</a>',
        ),
        'address_milford' => array(
          '#attributes' => array(
            'class' => array('address', 'dingmans'),
          ),
          '#theme_wrappers' => array('container'),
          '#markup' => '<span class="street">205 E. Harford St.</span><span class="city-state-zip">Milford, PA 18337</span><a class="phone" href="tel:18772969921">1-877-296-9921</a><a class="phone" href="tel:5702969921">(570) 296-9921</a>',
        ),
        'copyright' => array(
          '#attributes' => array(
            'class' => array('copyright'),
          ),
          '#theme_wrappers' => array('container'),
          '#markup' => 'Each Office is Independently Owned and Operated. &copy; ' . date('Y') . ' Century 21 Real Estate LLC.</br>CENTURY 21&reg; is a registered trademark licensed to Century 21 Real Estate LLC.</br>Equal Housing Opportunity.',
        ),
      );
      break;
  }
  return $block;
}

/**
 * Implements hook_workbench_content_alter().
 */
function c21_workbench_content_alter(&$output) {
  if (module_exists('c21_listings')) {
    $output['c21_workbench_reports'] = array(
      '#title' => t('Reports'),
      '#attributes' => array(
        'class' => array('left', 'clearfix'),
      ),
      'report_links' => array('#markup' => c21_listings_reports_links()),
      '#theme' => 'workbench_element',
    );
    $output['#attached']['css'][] = drupal_get_path('module', 'c21') . '/css/c21_workbench.css';
    unset($output['workbench_current_user']);
  }

  $output['c21_workbench_edits_by_user'] = $output['workbench_edited'];
  $output['c21_workbench_edits_by_user']['#view'] = 'c21_workbench_edits_by_user';
  unset($output['workbench_edited']);

  $output['c21_workbench_recent_content'] = $output['workbench_recent_content'];
  $output['c21_workbench_recent_content']['#view'] = 'c21_workbench_recent_content';
  unset($output['workbench_recent_content']);

}

/**
 * Implements hook_date_formats().
 */
function c21_date_formats() {
  $formats = array();

  $formats[] = array(
    'type' => C21_DATE_TYPE_VERY_SHORT,
    'format' => C21_DATE_FORMAT_VERY_SHORT,
    'locales' => array(),
  );
  $formats[] = array(
    'type' => 'short',
    'format' => C21_DATE_FORMAT_SHORT,
    'locales' => array(),
  );
  $formats[] = array(
    'type' => 'medium',
    'format' => C21_DATE_FORMAT_MEDIUM,
    'locales' => array(),
  );
  $formats[] = array(
    'type' => 'long',
    'format' => C21_DATE_FORMAT_LONG,
    'locales' => array(),
  );
  $formats[] = array(
    'type' => C21_DATE_TYPE_VERY_LONG,
    'format' => C21_DATE_FORMAT_VERY_LONG,
    'locales' => array(),
  );

  return $formats;
}

/**
 * Implements hook_date_format_types().
 */
function c21_date_format_types() {
  $types = array();
  $types[C21_DATE_TYPE_VERY_SHORT] = t('Very Short');
  $types[C21_DATE_TYPE_VERY_LONG] = t('Very Long');
  return $types;
}
