<?php
/**
 * @file
 * Code for the C21 Listings feature.
 */

include_once 'c21_listings.features.inc';

function c21_listings_menu() {
  $items['ajax/agents'] = array(
    'title' => 'List Agents',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access administration pages'),
    'page callback' => 'c21_listing_get_agents',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function c21_listings_theme($existing, $type, $theme, $path) {
  $theme_hooks = array(
    'c21_listings_render_rooms_group' => array(
      'render element' => 'form',
      'file' => 'theme/c21_listings_forms.inc',
    ),
  );

  return $theme_hooks;
}

/**
 * Implements hook_node_view().
 */
function c21_listings_node_view($node, $view_mode) {
  if ($node->type == 'listing') {
    // Add a map link.
    if (isset($node->field_listing_lot[LANGUAGE_NONE][0]['safe_value']) && isset($node->field_listing_street[LANGUAGE_NONE][0]['safe_value']) && isset($node->field_listing_township[LANGUAGE_NONE][0]['taxonomy_term']->name)) {
      $lot = $node->field_listing_lot[LANGUAGE_NONE][0]['safe_value'];
      $street = $node->field_listing_street[LANGUAGE_NONE][0]['safe_value'];
      $town = $node->field_listing_township[LANGUAGE_NONE][0]['taxonomy_term']->name;

      $links['c21_map_link'] = array(
        'title' => t('See map'),
        'href' => 'http://maps.google.com/maps',
        'query' => array(
          'q' => $lot . ' ' . $street . ', ' . $town . ', PA', // Search query.
          'hl' => 'en', // Language.
          'iwloc' => 'A', // Information Bubble [A|''].
          'z' => 12, // Zoom.
          't' => 'm', // Map type.
        ),
        'attributes' => array(
          'target' => '_blank',
        ),
      );

      $link_content = array(
        '#theme' => 'links',
        '#links' => $links,
        '#attributes' => array('class' => array('links', 'inline')),
      );

      $node->content['links']['c21_map_link'] = $link_content;
    }

    // Add the virtual tour link.
    if (!empty($node->field_listing_virtual_tour)) {
      // drupal_add_css(drupal_get_path('module', 'print') . '/css/printlinks.css'); @todo: add css for virtual tours
      $links['c21_virtual_tour_link'] = $node->field_listing_virtual_tour[LANGUAGE_NONE][0];
      $links['c21_virtual_tour_link']['title'] = t('Take a virtual tour');
      $links['c21_virtual_tour_link']['href'] = $links['c21_virtual_tour_link']['url'];

      $link_content = array(
        '#theme' => 'links',
        '#links' => $links,
        '#attributes' => array('class' => array('links', 'inline')),
      );

      $node->content['links']['c21_virtual_tour_link'] = $link_content;
    }

    if ($view_mode == 'full') {
      // Add js for the featured photo.
      // Using #attached causes borealis to stop working ?!?
      drupal_add_js(drupal_get_path('module','c21_listings') . '/js/c21_listings.js', array('scope' => 'footer'));
    }

  }
}

/**
 * Implements hook_field_formatter_info().
 */
function c21_listings_field_formatter_info() {
  $info = array(
    'listing_id' => array(
      'label' => t('Listing Id'),
      'field types' => array('text'),
      'description' => t('Displays text as a Listing Id by appending "-[nid]".'),
    ),
    'us_phone_number' => array(
      'label' => t('Telephone Number (US)'),
      'field types' => array('text'),
      'description' => t('Displays text as a tel: link'),
    ),
  );

  return $info;
}

/**
 * Implements hook_field_formatter_view().
 */
function c21_listings_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  switch ($display['type']) {
    case 'listing_id':
      foreach ($items as $delta => $item) {
        $element[$delta]['#markup'] = strtoupper($item['safe_value']) . '-' . $entity->nid;
      }
      break;
    case 'us_phone_number':
      foreach ($items as $delta => $item) {
        $element[$delta]['#theme'] = 'link';
        $element[$delta]['#text'] = $item['safe_value'];
        $element[$delta]['#path'] = _c21_format_phone_number_link($item['safe_value']);
        $element[$delta]['#options'] = array(
          'attributes' => array('class' => array('phone-number us-phone-number')),
          'html' => FALSE,
        );
      }
  }
  return $element;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function c21_listings_form_agent_node_form_alter(&$form, $fom_state) {
  // Set a placeholder for the name field.
  $form['title']['#placeholder'] = t('Roy B. Hull, Owner');
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function c21_listings_form_listing_node_form_alter(&$form, &$form_state) {
  // Add custom CSS and JS files for this form.
  $form['#attached']['css'][] = drupal_get_path('module', 'c21_listings') . '/css/c21_listings_forms.css';
  $form['#attached']['js'][] = drupal_get_path('module', 'c21_listings') . '/js/c21_listings_forms.js';

  // Add the listing id number as a suffix to the listing id prefix field.
  $form['field_listing_id_prefix'][LANGUAGE_NONE][0]['value']['#field_suffix'] = ' &ndash; ' . (isset($form['#node']->nid) ? $form['#node']->nid : '#####');

  // MLS # should only be displayed for "exclusive" listings.
  $form['field_listing_mls']['#states'] = array(
    'visible' => array(
      '#edit-field-listing-type-und' => array(
        array('value' => 'exclusive'),
        array('value' => 'exclusive_right'),
      ),
    ),
  );

  // Add some classes to the agent fields.
  $form['field_listing_agent']['#attributes']['class'][] = 'field-agents';
  $form['field_listing_sale_agent']['#attributes']['class'][] = 'field-agents';

  // Remove the fieldset from date fields.
  $form['field_listing_list_date'][LANGUAGE_NONE][0]['#theme_wrappers'] = array('form_element');
  $form['field_listing_year_built'][LANGUAGE_NONE][0]['#theme_wrappers'] = array('form_element');
  $form['field_listing_closing_date'][LANGUAGE_NONE][0]['#theme_wrappers'] = array('form_element');

  // Rename the publishing options field.
  $form['options']['#title'] = t('Listing options');
  $form['options']['status']['#title'] = t('Active listing');
  $form['options']['promote']['#title'] = t('Featured listing');
  $form['options']['sticky']['#access'] = FALSE;

  $form['field_listing_bathrooms'][LANGUAGE_NONE][0]['value']['#step'] = .5;
  $form['field_listing_acreage'][LANGUAGE_NONE][0]['value']['#step'] = .001;

  // Hide the "legacy data" field if its empty and for non-admins.
  $form['field_listing_legacy_data']['#disabled'] = TRUE;
  if (!user_access('administer site configuration') || empty($form['field_listing_legacy_data'][LANGUAGE_NONE][0]['value']['#default_value'])) {
    $form['field_listing_legacy_data']['#access'] = FALSE;
  }

}

/**
 * Implements hook_field_group_build_pre_render_alter().
 */
function c21_listings_field_group_build_pre_render_alter(&$element) {
  $element['group_listing_details']['group_listing_measurements']['group_listing_rooms']['#theme'][] = 'c21_listings_render_rooms_group';
}

/**
 * Implements hook_date_combo_process_alter().
 */
function c21_listings_date_combo_process_alter(&$element, $form_state, $context) {
  $element['show_todate']['#access'] = FALSE;
  unset($element['value']['#description']);
  unset($element['value']['#attributes']);
  unset($element['value2']['#description']);
  unset($element['value2']['#title']);
  unset($element['value2']['#attributes']);

  $element['value']['#wrapper_attributes']['class'] = array('start-date-wrapper');
  $element['value2']['#wrapper_attributes']['class'] = array('end-date-wrapper');
}

/**
 * Implements hook_date_popup_process_alter().
 */
function c21_listings_date_popup_process_alter(&$element, $form_state, $context) {
  if ($context['form'][$element['#field']['field_name']][LANGUAGE_NONE][0]['#type'] == 'date_combo') {
    if ($element['#date_title'] == 'List Date End date' && $context['form'][$element['#field']['field_name']][LANGUAGE_NONE][0]['#type'] == 'date_combo') {
      $element['#prefix'] = '<span class="fromto">to</span>';
    }
    $element['date']['#description'] = '';
  }

}

/**
 * Returns a list of agents with basic meta data.
 * @return array
 *   An array agents, keyed by nid, including 'full_name', 'last_name',
 *   'current_office', and 'status'.
 */
function c21_listing_get_agents() {
  $agents = array();

  $result = db_select('node', 'n')
    ->fields('n', array('nid'))
    ->condition('type', 'agent')
    ->condition('status', 1)
    ->orderBy('title')
    ->execute();

  while ($record = $result->fetchAssoc()) {
    $agent = node_load($record['nid']);

    $agents[$record['nid']] = array(
      'full_name' => $agent->title,
      'last_name' => $agent->name,
      'current_office' => $agent->field_agent_primary_office[LANGUAGE_NONE][0]['value'],
      'status' => $agent->field_agent_status[LANGUAGE_NONE][0]['value'],
    );
  }

  print drupal_json_output($agents);
  exit();
}

/**
 * Theme function for the listing_id field formatter.
 */
function theme_c21_listings_listing_id($variables) {
  return strtoupper($variables['prefix']) . '-' . $variables['nid'];
}

/**
 * Format a phone number to be appropraite for use in the href of a tel: link.
 *
 * @param  string $phone_number
 *   A human readible phone number.
 *
 * @return string
 *   The formatted phone number beginning with "tel:". The strings "ext" and "x"
 *   will be replaced with a "+".
 */
function _c21_format_phone_number_link($phone_number) {
  $formatted_phone_number = preg_replace("/x|ext|ext./i", '+', $phone_number);
  $formatted_phone_number = preg_replace("/[^0-9,+]/i", '', $formatted_phone_number);

  return 'tel:' . $formatted_phone_number;
}


