<?php
/**
 * @file
 * Code for the c21 Search feature.
 */

include_once 'c21_search.features.inc';

/**
 * Implements hook_apachesolr_index_document_build_ENTITY_TYPE().
 */
function c21_search_apachesolr_index_document_build_listing(ApacheSolrDocument &$document, $entity, $env_id) {
  if ($entity->type == 'listing') {
    $document->addField('ts_field_listing_id', $entity->field_listing_id_prefix['und'][0]['value'] . '-' . $entity->nid);
    $document->addField('ts_field_mls', $entity->field_listing_mls['und'][0]['value']);
    $document->addField('fs_field_list_price', $entity->field_listing_list_price['und'][0]['value']);
    $document->addField('is_field_bedrooms', $entity->field_listing_bedrooms['und'][0]['value']);
    $document->addField('fs_field_bathrooms', $entity->field_listing_bathrooms['und'][0]['value']);
    $document->addField('fs_field_acreage', $entity->field_listing_acreage['und'][0]['value']);
    $document->addField('is_field_sq_ft', $entity->field_listing_sq_ft_above['und'][0]['value'] + $entity->field_listing_sq_ft_below['und'][0]['value']);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function c21_search_form_views_exposed_form_alter(&$form, &$form_state) {
  switch ($form['#id']) {
    case 'views-exposed-form-c21-search-listings-page':
      // Add some placeholder text to the search field.
      $form['keyword']['#placeholder'] = t('Listing ID, MLS#, keywords, etc.');

      // Add javascript to handle the facet sliders.
      // $form['#attached']['js'][] = drupal_get_path('theme','escrow') . '/js/jquery.hammer.min.js';
      $form['#attached']['js'][] = drupal_get_path('module', 'c21_search') . '/js/c21_search.js';

      // Add a toggle.
      $form['toggle'] = array(
        '#type' => 'markup',
        '#markup' => '<div class="toggle">' . t('Search') . '</div>',
      );
      $element_to_insert['filter-toggle'] = array(
        'value' => 'toggle',
      );
      $form['#info'] = array_merge($element_to_insert, $form['#info']);
      break;
  }
}
