<?php
/**
 * @file
 * Code for the c21 Search feature.
 */

include_once 'c21_search.features.inc';

/**
 * Integrates hook_apachesolr_index_document_build_ENTITYTYPE().
 */
function c21_search_apachesolr_index_document_build_listing(ApacheSolrDocument &$document, $entity, $env_id) {
  if ($entity->type == 'listing') {
    $document->addField('ts_field_listing_id', $entity->field_listing_id_prefix['und'][0]['value'] . '-' . $entity->nid);
    $document->addField('ts_field_mls', $entity->field_listing_mls['und'][0]['value']);
    $document->addField('fs_field_list_price', $entity->field_listing_list_price['und'][0]['value']);
    $document->addField('is_field_bedrooms', $entity->field_listing_bedrooms['und'][0]['value']);
    $document->addField('fs_field_bathrooms', $entity->field_listing_bathrooms['und'][0]['value']);
    $document->addField('fs_field_acreage', $entity->field_listing_acreage['und'][0]['value']);
    $document->addField('is_field_sq_ft', $entity->field_listing_sq_ft_above['und'][0]['value'] + $entity->field_listing_sq_ft_below['und'][0]['value']);
  }
}
