<?php

/**
 * Implements hook_install().
 */
function c21_search_install() {
  // Delete the default solr environment that comes with the solr module.
  apachesolr_environment_delete('solr');
}

/**
 * Truncate the search_* tables.
 */
function c21_search_update_7001() {
  $tables = array('search_dataset', 'search_index', 'search_total', 'search_node_links');

  foreach($tables as $table) {
    db_truncate($table);
  }
}
